### ISSUE TITLE
Remove `rem` from line-height mixin

### ISSUE THREAD

**Issue by mikeriley131** [alectro/SCSScale#1]
This is great. Thanks for putting this together.

If I may make one suggestion, I would remove `rem` from the line-height mixin (_mixins.scss, line 10). See: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values

```
@function calculateRem($lheight) {
  $remSize: $lheight / 16px;
//Default font size on html element is 100%, equivalent to 16px;
  @return #{$remSize}rem;
}
```

should be

```
@function calculateRem($lheight) {
  $remSize: $lheight / 16px;
//Default font size on html element is 100%, equivalent to 16px;
  @return #{$remSize};
}
```

**Comment by alectro** [comment]
Thanks @mikeriley131 for noticing this!

Now **line-height** only displays unitless values as in <number>.
